apiVersion: apps/v1
kind: Deployment
metadata:
    name: ecommerce-app-deployment
    labels:
        app: ecommerce-app
spec:
    replicas: 3
    selector:
        matchLabels:
            app: ecommerce-app
    template:
        metadata:
            labels:
                app: ecommerce-app
        spec:
            containers:
                - name: ecommerce-app
                  image: bhardwajakash/ecommerce:latest
                  ports:
                    - name: http
                      containerPort: 80
                      protocol: TCP
---
apiVersion: v1
kind: Service
metadata: 
    name: ecommerce-app
spec:
    type: NodePort
    selector:
        app: ecommerce-app
    ports:
        - protocol: TCP
          nodePort: 30158
          port: 80
          targetPort: 80