apiVersion: apps/v1
kind: Deployment
metadata:
    name: ecommerce-app-deployment
    namespace: kubernetes-cluster-akashbhardwaj
    labels:
        app: ecommerce-app
spec:
    replicas: 4
    selector:
        matchLabels:
            app: ecommerce-app
    template:
        metadata:
            labels:
                app: ecommerce-app
        spec:
            containers:
                - name: ecommerce-app
                  image: bhardwajakash/ecommerce:latest
                  ports:
                    - name: http
                      containerPort: 80
                      protocol: TCP
