apiVersion: v1
kind: Service
metadata: 
    name: ecommerce-app
    namespace: kubernetes-cluster-akashbhardwaj
spec:
    type: NodePort
    selector:
        app: ecommerce-app
    ports:
        - protocol: TCP
          nodePort: 30157
          port: 80
          targetPort: 80