apiVersion: v1
kind: Service
metadata: 
    name: ecommerce-app-develop
    namespace: kubernetes-cluster-akashbhardwaj
    labels:
        app: ecommerce-app-develop
spec:
    type: NodePort
    selector:
        app: ecommerce-app-develop
    ports:
        - protocol: TCP
          nodePort: 30158
          port: 80
          targetPort: 80